platform :ios,'8.0'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'MJRefresh', '~> 1.4.7'
pod 'MJExtension'
pod 'UMengSocial', '~> 4.4'
pod 'UMengAnalytics-NO-IDFA'
pod 'EaseMobSDK'
pod 'BaiduMapKit'
pod 'ZBarSDK'
pod 'NJKWebViewProgress'
pod 'OpenUDID'
pod 'IQKeyboardManager', '~> 3.3.7'
pod 'MJPhotoBrowser'
pod 'DZNSegmentedControl'
pod 'BEMSimpleLineGraph'
pod 'VGParallaxHeader'
pod 'iOS-AlipaySDK'
pod 'iOS-WechatSDK'